### ISSUE TITLE
join forces?

### ISSUE THREAD

**Issue by bjarthur** [JuliaIO/Suppressor.jl#10]
this [PR](https://github.com/JuliaLang/julia/pull/16213) to julia base provides built-in functionality similar to Logging.jl.  would greatly appreciate your comments.

**Comment by Ismael-VC** [comment]
@bjarthur sorry for the late response, about joining forces... definitely! Trying to make this macros work has already been an ordeal, I've always thought they should be in base, thank you for bringing that PR to my attention.

Regards.
