### ISSUE TITLE
Enable AppVeyor CI for Windows testing.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaIO/Suppressor.jl#19]

**Comment by iamed2** [comment]
I believe anyone in the JuliaIO organization (e.g., @ararslan) can enable AppVeyor for this package under the JuliaIO organization.

**Comment by ararslan** [comment]
AppVeyor runs on personal accounts rather than per-org. Ismael, can you set it up to run on your account?

**Comment by iamed2** [comment]
~@ararslan It can run per-org, you just need to sign in with your personal account.~

~https://www.dropbox.com/s/tot1yny87vhetuc/Screenshot%202018-02-23%2015.29.41.png?dl=0~

EDIT: NVM, we manually set up a team before.

**Comment by Ismael-VC** [comment]
Thanks Alex, I have set it up from my personal account :+1: 

See #20
