### ISSUE TITLE
Tag latest request

### ISSUE THREAD

**Issue by GearsAD** [JuliaIO/Suppressor.jl#24]
Hi,

Thanks for adding the library, saved a lot of work!

Could you tag latest so that Pkg.add("Suppressor") includes the @color_output source code?

**Comment by GearsAD** [comment]
Hi, just a friendly reminder

**Comment by ssfrr** [comment]
[A release](https://github.com/JuliaIO/Suppressor.jl/releases/tag/v0.1.0) was made in May, so this issue can be closed

**Comment by Ismael-VC** [comment]
Done.
