### ISSUE TITLE
1.0 support?

### ISSUE THREAD

**Issue by carstenbauer** [JuliaIO/Suppressor.jl#29]
Any plans to fully support 1.0?

First example on the github page:

```julia
julia> @suppress begin
                  println("This string doesn't get printed!")
                             warn("This warning is ignored.")
                                    end
ERROR: UndefVarError: warn not defined
```

Also, from [this](https://discourse.julialang.org/t/is-there-a-way-to-suppress-method-overwritten-warnings/3233/10?u=crstnbr) discourse thread:

```julia
julia> f(x) = 1                                                      
f (generic function with 1 method)                                   
                                                                     
julia> @suppress f(x) = 2                                            
(::getfield(Main, Symbol("#f#21"))) (generic function with 1 method) 
                                                                     
julia> f(3)                                                          
1                                                                    
```

Old behavior:
```julia
julia> f(x) = 1
f (generic function with 1 method)

julia> @suppress f(x) = 2
2
```

**Comment by iamed2** [comment]
In the second example, the old behaviour seems like its own problem to me.

But the new behaviour should overwrite the method, yes.

The first example just needs to be updated to the new syntax:

```
julia> @suppress begin
           println("foo")
           @warn "This warning is ignored"
       end

julia>
```

**Comment by ssfrr** [comment]
I haven't had much time to work on maintenance for this project lately, and to be honest that isn't likely to change very soon.

In your 2nd example, what is the output of `f(3)` afterwards in the old behavior? i.e. did it overwrite the method or not? The desired behavior is that it _should_ overwrite the method (though maybe it doesn't).

In the new version I suspect it's an escaping issue (the macro needs to escape the given code so that it's executed in the caller's context).

**Comment by iamed2** [comment]
README updated in https://github.com/JuliaIO/Suppressor.jl/pull/30

**Comment by thofma** [comment]
@ssfrr The method is not overwritten, which is not the desired behavior.

**Comment by schlichtanders** [comment]
just stumbled upon this that method definition are completely ignored in the current `Suppressor.jl` took me a while to figure out that my problem is due to that

@ssfrr can you fix ``@suppress`` so that method definitions work again?

**Comment by ssfrr** [comment]
Unfortunately I don't really have time to commit to maintaining this package right now.

I agree it should be fixed though - if someone has time time to write a test case and a fix for it I could take a look and merge it.

Some of the use-cases for this package have been subsumed into more convenient `redirect_stdout` and `redirect_stderr` methods in `Base` that accept a `do` block, so I think this package isn't used as widely anymore. enabling and disabling color still seem useful, as are suppressing output without capturing it.

**Comment by omus** [comment]
Julia 1.0 support added in the 0.2.0 release
