### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ssfrr** [JuliaIO/Suppressor.jl#4]
Would you mind tagging a new release? I've got another package that's now using the new `capture_*` functionality in its tests, and I'd like to avoid pulling from master. Thanks!

**Comment by Ismael-VC** [comment]
@ssfrr I'm sorry, not used to maintaining a public package, so I forgot to do that, even when I had it in the project [dashboard](https://github.com/Ismael-VC/Suppressor.jl/projects/1). You can see the current tagging progress here:
- https://github.com/JuliaLang/METADATA.jl/pull/6790

Thank you very much of reminding me to do this!

**Comment by ssfrr** [comment]
no prob! thanks for tagging.

**Comment by Ismael-VC** [comment]
Closed by: https://github.com/JuliaLang/METADATA.jl/pull/6790
