### ISSUE TITLE
`_logger` not defined

### ISSUE THREAD

**Issue by johroj** [JuliaIO/Suppressor.jl#55]
PortAudio.jl fails during precompilation when using the latest version of Suppessor.jl. 

The reason seems to be it calls `@capture_err` within `__init__()`, causing 
```
ERROR: LoadError: InitError: UndefVarError: `_logger` not defined
```

Indeed, `_logger` is not assigned in all branches of the if-statements just above the line 

https://github.com/JuliaIO/Suppressor.jl/blob/20025953ed61a57e045fee89df6cd831c2888b3c/src/Suppressor.jl#L39

**Comment by aviks** [comment]
I'm seeing this as well. I can confirm fixing Supressor to v0.2.0 make the problem go away. 

The problematic line seems to be last touched in https://github.com/JuliaIO/Suppressor.jl/pull/53 

cc: @Drvi @quinnj

**Comment by Drvi** [comment]
Ah, I see the problem, will look into it
